# GKE Service Account in relevant GKE namespace to run Mutating Admission webhook from
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ .Values.webhookSA }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ tpl ($value | toString) $ }}
  {{- end }}
---
# GKE Service Account in relevant GKE namespace to create K8S Secret with TLS type that includes
# corresponding client certificate signed by K8S CA and private key
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.certificatorSA }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ tpl ($value | toString) $ }}
  {{- end }}
