version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cmd/token-injector"
    schedule:
      interval: "weekly"
    reviewers:
    - "ealebed"
  - package-ecosystem: "gomod"
    directory: "/cmd/token-injector-webhook"
    schedule:
      interval: "weekly"
    reviewers:
    - "ealebed"
