version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: chore
    groups:
      all:
        patterns:
          - "*"
    labels:
      - automated-dependency-updates
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: /cmd/token-injector
    schedule:
      interval: monthly
    commit-message:
      prefix: chore

  - package-ecosystem: gomod
    commit-message:
      prefix: chore
    directory: /cmd/token-injector-webhook
    schedule:
      interval: monthly
