# Default values for webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# GKE namespace for running Mutating Admission webhook and Certificator tool.
namespace: mex-aws-token-injector

# GKE Service Account in relevant GKE namespace to run Mutating Admission webhook from.
webhookSA: token-injector-admission-webhook-sa

# GKE Service Account in relevant GKE namespace to create K8S Secret with TLS type that
# includes corresponding client certificate signed by K8S CA and private key.
certificatorSA: token-injector-admission-webhook-cert-sa

# Service for admission webhook
webhookService: token-injector-admission-webhook-svc

# Container images
webhookImage: ""
tokenRequesterImage: ""
certificatorImage: ""

# Common labels for Mutating Admission webhook and Certificator tool
labels:
  app: token-injector-admission-webhook

# PEM encoded CA bundle which will be used to validate the webhook’s server certificate
# To pass the value 'in runtime' when running helm command you can use `--set` parameter, e.g.:
# helm install ... --set apiserverCABundle=$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}')
apiserverCABundle: ""
