# Job for creating secrets with client certificate which is signed by K8S CA and private key
# More details: https://github.com/ealebed/admission-webhook-certificator
apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-cert-setup
  namespace: webhook
spec:
  template:
    spec:
      serviceAccountName: webhook-cert-sa
      containers:
        - name: webhook-cert-setup
          image: ealebed/certificator:latest
          args:
            - "certify"
            - "--service"
            - "admission-webhook-svc"
            - "--namespace"
            - "webhook"
            - "--secret"
            - "webhook-certs"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 0
