# Service for admission webhook
apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-svc
  namespace: webhook
  labels:
    app: admission-webhook
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: admission-webhook
