# Binding Cluster Role for Mutating Admission webhook to relevant GKE Service Account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-webhook-crb 
  labels:
    app: admission-webhook
subjects:
- kind: ServiceAccount
  name: webhook-sa
  namespace: webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-webhook-cr
---
# Binding Cluster Role for creating secrets to relevant GKE Service Account
# More details: https://github.com/ealebed/admission-webhook-certificator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-cert-sa-crb
  labels:
    app: admission-webhook
subjects:
- kind: ServiceAccount
  name: webhook-cert-sa
  namespace: webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-cert-sa-cr

