# GKE Service Account in relevant GKE namespace to run Mutating Admission webhook from
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-sa
  namespace: webhook
  labels:
    app: admission-webhook
---
# GKE Service Account in relevant GKE namespace to create K8S Secret with TLS type that includes
# corresponding client certificate signed by K8S CA and private key
# More details: https://github.com/ealebed/admission-webhook-certificator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-cert-sa
  namespace: webhook
  labels:
    app: admission-webhook