# Mutating Webhook Configuration for admission webhook
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-admission-webhook-cfg
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ tpl ($value | toString) $ }}
  {{- end }}
webhooks:
  - name: admission-webhook.example.com
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: {{ .Values.webhookService }}
        namespace: {{ .Values.namespace }}
        path: "/pods"
      caBundle: {{ .Values.apiserverCABundle }}
    objectSelector:
      matchExpressions:
        - key: admission.token-injector/enabled
          operator: Exists
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
        scope: "Namespaced"
    failurePolicy: Ignore
