name: 'Build and Push Container Images'

"on":
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    paths:
      - helm-chart/**

jobs:
  build_and_push_token_injector_chart:
    name: Build and push token-injector chart
    runs-on: ubuntu-latest
    permissions:
      # required to clone repository
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
      
      # Package, push, and tag token-injector chart to GH Pages
      - name: Package, push, and tag token-injector chart
        uses: helm/chart-releaser-action@v1.7.0
        # https://github.com/helm/chart-releaser-action#inputs
        with:
          charts_dir: helm-chart
          # Skip package upload if release already exists
          # so we can merge to main w/o triggering a release commit
          skip_existing: true
          # Helm does not support 2nd authentication to GH Releases
          # (after fetching from the index.yaml file)
          # so we need to store the .tgz package in the gh-pages branch
          packages_with_index: true
        env:
          CR_TOKEN: ${{ github.token }}
